# Copyright FUJITSU LIMITED 2014.

- name: create download directory
  file: "state=directory path=/usr/local/src/elasticsearch-{{ version }} owner=root group=root recurse=yes"

- name: download elasticsearch-{{ version }}.tar.gz
  get_url: url=https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-{{ version }}.tar.gz dest=/usr/local/src/elasticsearch-{{ version }}/elasticsearch-{{ version }}.tar.gz

- name: download elasticsearch-{{ version }}.tar.gz
  get_url: url=https://github.com/elasticsearch/elasticsearch-servicewrapper/archive/master.zip dest=/usr/local/src/elasticsearch-{{ version }}/master.zip

- name: deploy elasticsearch
  unarchive: src=/usr/local/src/elasticsearch-{{ version }}/elasticsearch-{{ version }}.tar.gz dest=/opt copy=no

- name: expand master.zip
  unarchive: src=/usr/local/src/elasticsearch-{{ version }}/master.zip dest=/usr/local/src/elasticsearch-{{ version }} copy=no

- name: deploy service directory
  command: mv /usr/local/src/elasticsearch-{{ version }}/elasticsearch-servicewrapper-master/service /opt/elasticsearch-{{ version }}/bin creates="/opt/elasticsearch-{{ version }}/bin/service"

- name: deploy elasticsearch.yml
  template: src=./resource/es/opt/elasticsearch-{{ version }}/config/elasticsearch.yml.j2 dest=/opt/elasticsearch-{{ version }}/config/elasticsearch.yml owner=elasticsearch group=elasticsearch mode=0644

- name: deploy elasticsearch.conf
  template: src=./resource/es/opt/elasticsearch-{{ version }}/bin/service/elasticsearch.conf.j2 dest=/opt/elasticsearch-{{ version }}/bin/service/elasticsearch.conf owner=elasticsearch group=elasticsearch mode=0644

- name: change /opt/elasticsearch-{{ version }}'s owner into elasticsearch
  file: "path=/opt/elasticsearch-{{ version }} owner=elasticsearch group=elasticsearch recurse=yes"

- name: install service
  command: "/opt/elasticsearch-{{ version }}/bin/service/elasticsearch install creates=/etc/init.d/elasticsearch"

- name: deploy startup script
  copy: src=./resource/es/opt/elasticsearch-{{ version }}/bin/service/elasticsearch dest=/opt/elasticsearch-{{ version }}/bin/service/elasticsearch owner=elasticsearch group=elasticsearch mode=0755

- name: deploy /etc/logrotate.d/es-service
  copy: src=./resource/es/etc/logrotate.d/es-service dest=/etc/logrotate.d/es-service owner=root group=root mode=0644
