# Copyright FUJITSU LIMITED 2018.

personium_plugin_sample_version : master

personium_ex_httpclient_version : master

personium_ex_mailsender_version : master

personium_ex_slack_messenger_version : master

personium_ex_ew_services_version : master

personium_app_unit_manager_version : master