# Copyright FUJITSU LIMITED 2015-2018.

- name: Deploy /etc/postfix
  copy: src=./resource/common/etc/postfix dest=/etc owner=root group=root
  notify:
  - reload postfix

- name: Restart postfix
  systemd:
    name: postfix
    state: restarted
