# Copyright FUJITSU LIMITED 2014.

- name: download apache-maven-3.2.5-bin.zip
  get_url: url=http://ftp.yz.yamagata-u.ac.jp/pub/network/apache/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.zip dest=/tmp mode=0440

- name: expand apache-maven-3.2.5-bin.zip
  unarchive: src=/tmp/apache-maven-3.2.5-bin.zip dest=/opt copy=no

- name: set maven proxy valid or invalid
  command: 'python -c "import sys;print(\"true\") if len(sys.argv) == 2 else \"false\"" {{http_proxy}}'
  register: maven_proxy_active

- name: set maven proxy's host
  command: 'python -c "import sys;import urlparse;print(\"\") if (len(sys.argv) == 1) or (urlparse.urlparse(sys.argv[1]).hostname == None) else urlparse.urlparse(sys.argv[1]).hostname" {{http_proxy}}'
  register: maven_proxy_host

- name: set maven proxy's port
  command: 'python -c "import sys;import urlparse;print(\"\") if (len(sys.argv) == 1) or (urlparse.urlparse(sys.argv[1]).port == None) else urlparse.urlparse(sys.argv[1]).port" {{http_proxy}}'
  register: maven_proxy_port

- name: set maven proxy's username
  command: 'python -c "import sys;import urlparse;print(\"\") if (len(sys.argv) == 1) or (urlparse.urlparse(sys.argv[1]).username == None) else urlparse.urlparse(sys.argv[1]).username" {{http_proxy}}'
  register: maven_proxy_username

- name: set maven proxy's password
  command: 'python -c "import sys;import urlparse;print(\"\") if (len(sys.argv) == 1) or (urlparse.urlparse(sys.argv[1]).password == None) else urlparse.urlparse(sys.argv[1]).password" {{http_proxy}}'
  register: maven_proxy_password

- name: create .m2 directory for root
  file: "state=directory path=/root/.m2 owner=root group=root"

- name: deploy maven's setting.xml
  template: src=./resource/common/settings.xml.j2 dest=/root/.m2/settings.xml owner=root group=root mode=0644
