# Copyright FUJITSU LIMITED 2015-2018.

- name: build module
  command: /opt/apache-maven-3.3.9/bin/mvn package -Dmaven.test.skip=true
  args:
    chdir: /tmp/personium-{{ build_mod }}
    creates: /root/ansible/resource/ap/opt/tomcat/webapps/personium-{{ build_mod }}.war
  environment:
    JAVA_HOME: /opt/jdk
  register: result
  until: result.stdout.find('BUILD SUCCESS') != -1 or result.stdout.find('skipped, since') != -1
  retries: 3
  delay: 20

- name: move module
  command: mv /tmp/personium-{{ build_mod }}/target/personium-{{ build_mod }}.war /root/ansible/resource/ap/opt/tomcat/webapps/personium-{{ build_mod }}.war
  args:
    creates: /root/ansible/resource/ap/opt/tomcat/webapps/personium-{{ build_mod }}.war
