# Copyright FUJITSU LIMITED 2014.

- hosts: localhost
  gather_facts: no
  sudo: yes
  vars_files: 
    - ./group_vars/common.yml
  tasks:
    - include: ./tasks/common/init_jdk.yml
    - include: ./tasks/common/init_telnet.yml
    - include: ./tasks/common/init_maven.yml
