# Copyright FUJITSU LIMITED 2014.

- hosts: localhost
  gather_facts: no
  sudo: yes
  vars_files: 
    - ./group_vars/common.yml
    - ./group_vars/es.yml
  tasks:
    - include: ./tasks/common/init_process_account_common.yml
      vars:
        username: elasticsearch
        groupname: elasticsearch
        uid: 2060
        gid: 2060
        comment: Elasticsearch Administrator
    - include: ./tasks/es/init_directory.yml
    - include: ./tasks/es/install_elasticsearch.yml
    - include: ./tasks/es/init_service_elasticsearch.yml
