# Copyright FUJITSU LIMITED 2015-2018.

- include: ./tasks/common/init_process_account_personium.yml
- include: ./tasks/nfs/init_personium-dir.yml
- include: ./tasks/nfs/init_logback.yml

- include: ./tasks/nfs/init_memcached_env_os.yml
  when: cache_in_nfs
- include: ./tasks/nfs/init_memcached_install.yml
  when: cache_in_nfs
- include: ./tasks/nfs/init_memcached_setup.yml
  when: cache_in_nfs
