# Copyright FUJITSU LIMITED 2014.

- name: create download directory
  file: "state=directory path=/usr/local/src/tomcat owner=root group=root"

- name: download apache_tomcat_{{ tomcat_version }}.tar.gz
  get_url: url=http://archive.apache.org/dist/tomcat/tomcat-8/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz dest=/usr/local/src/tomcat/apache-tomcat-{{ tomcat_version }}.tar.gz

- name: unarchive apache_tomcat_{{ tomcat_version }}.tar.gz
  unarchive: src=/usr/local/src/tomcat/apache-tomcat-{{ tomcat_version }}.tar.gz dest=/usr/local/src/tomcat copy=no

- name: unarchive commons_daemon
  file: "state=directory path=/usr/local/src/tomcat owner=root group=root"

- name: unarchive　commons_daemon_native.tar.gz
  unarchive: src=/usr/local/src/tomcat/apache-tomcat-{{ tomcat_version }}/bin/commons-daemon-native.tar.gz dest=/usr/local/src/tomcat copy=no

- name: commons_daemon を configure
  command: >
    ./configure
  environment:
    JAVA_HOME: "/opt/jdk"
  args:
    chdir: /usr/local/src/tomcat/commons-daemon-{{ commons_daemon_version }}-native-src/unix
    creates: /usr/local/src/tomcat/commons-daemon-{{ commons_daemon_version }}-native-src/unix/Makefile

- name: compile commons_daemon
  command: make
  args:
    chdir: /usr/local/src/tomcat/commons-daemon-{{ commons_daemon_version }}-native-src/unix
    creates: /usr/local/src/tomcat/commons-daemon-{{ commons_daemon_version }}-native-src/unix/jsvc

- name: deploy jsvc
  command: cp /usr/local/src/tomcat/commons-daemon-{{ commons_daemon_version }}-native-src/unix/jsvc /usr/local/src/tomcat/apache-tomcat-{{ tomcat_version }}/bin/ creates="/usr/local/src/tomcat/apache-tomcat-{{ tomcat_version }}/bin/jsvc"

- name: deploy tomcat undre /opt
  command: mv /usr/local/src/tomcat/apache-tomcat-{{ tomcat_version }} /opt/apache-tomcat-{{ tomcat_version }} creates="/opt/apache-tomcat-{{ tomcat_version }}"

- name: create /opt/apache-tomcat-{{ tomcat_version }} symlink named by /opt/tomcat
  file: state=link src=/opt/apache-tomcat-{{ tomcat_version }} dest=/opt/tomcat owner=root group=root mode=0777

- name: delete existing /opt/tomcat/logs
  file: state=absent path=/opt/tomcat/logs

- name: create /fj/tomcat directory
  file: "state=directory path=/fj/tomcat owner=glassfish group=glassfish"

- name: create /opt/disk1/tomcat directory
  file: "state=directory path=/opt/disk1/tomcat owner=root group=root"

- name: create /opt/disk1/tomcat/logs directory
  file: "state=directory path=/opt/disk1/tomcat/logs owner=glassfish group=glassfish"

- name: create /opt/disk1/tomcat/logs symlink named by /fj/tomcat/logs
  file: state=link src=/opt/disk1/tomcat/logs dest=/fj/tomcat/logs owner=root group=root mode=0777

- name: create /fj/tomcat/logs symlink named by /opt/tomcat/logs
  file: state=link src=/fj/tomcat/logs dest=/opt/tomcat/logs owner=root group=root mode=0777

- name: change /opt/tomcat/conf's owner into glassfish
  file: path=/opt/tomcat/conf owner=glassfish group=glassfish recurse=yes

- name: change /opt/tomcat/webapps's owner into glassfish
  file: path=/opt/tomcat/webapps owner=glassfish group=glassfish recurse=yes

- name: change /opt/tomcat/work's owner into glassfish
  file: path=/opt/tomcat/work owner=glassfish group=glassfish recurse=yes

- name: change /opt/tomcat/temp's owner into glassfish
  file: path=/opt/tomcat/temp owner=glassfish group=glassfish recurse=yes

- name: deploy boot script
  copy: src=./resource/web/etc/rc.d/init.d/tomcat dest=/etc/rc.d/init.d/tomcat owner=root group=root mode=755

- name: deploy environmental setting script 'setenv.sh'
  template: src=./resource/web/opt/tomcat/bin/setenv.sh.j2 dest=/opt/tomcat/bin/setenv.sh owner=glassfish group=glassfish mode=755

- name: deploy environmental setting script 'daemon.sh'
  copy: src=./resource/web/opt/tomcat/bin/daemon.sh dest=/opt/tomcat/bin/daemon.sh owner=glassfish group=glassfish mode=755


- name: deploy setting file(/opt/tomcat/conf/catalina.policy)
  copy: src=./resource/web/opt/tomcat/conf/catalina.policy dest=/opt/tomcat/conf/catalina.policy owner=glassfish group=glassfish mode=600

- name: deploy setting file(/opt/tomcat/conf/logging.properties)
  copy: src=./resource/web/opt/tomcat/conf/logging.properties dest=/opt/tomcat/conf/logging.properties owner=glassfish group=glassfish mode=600

- name: deploy setting file(/opt/tomcat/conf/server.xml)
  copy: src=./resource/web/opt/tomcat/conf/server.xml dest=/opt/tomcat/conf/server.xml owner=glassfish group=glassfish mode=600

- name: deploy setting file(/opt/tomcat/conf/tomcat-users.xml)
  copy: src=./resource/web/opt/tomcat/conf/tomcat-users.xml dest=/opt/tomcat/conf/tomcat-users.xml owner=glassfish group=glassfish mode=600

- name: register tomcat to service
  service: name=tomcat enabled=no

- name: deploy logrotate s setting file(/etc/logrotate.d/tomcat)
  copy: src=./resource/web/etc/logrotate.d/tomcat dest=/etc/logrotate.d/tomcat owner=root group=root mode=644


