# Copyright FUJITSU LIMITED 2014.

- name: deploy dc-engine/extensions
  copy: src=./resource/web/fj/18888/dc-engine/extensions dest=/fj/18888/dc-engine owner=glassfish group=glassfish mode=644

- name: obtain secret16
  command: cat /fj/dc-core/conf/token.key
  register: secret16

- name: obtain salt
  command: cat /fj/dc-core/conf/salt.key
  register: salt

- name: deploy dc-config.properties
  template: src=./resource/web/fj/dc-core/conf/18888/dc-config.properties.j2 dest=/fj/dc-core/conf/18888/dc-config.properties owner=root group=root mode=0644

- name: deploy logback-18888.xml
  copy: src=./resource/web/opt/logback/logback-18888.xml dest=/opt/logback/logback-18888.xml owner=glassfish group=glassfish mode=0644

- name: download personium.io
  get_url: url=https://github.com/personium/io/archive/master.zip dest=/tmp/io-master.zip mode=0440

- name: expand personium.io
  unarchive: src=/tmp/io-master.zip dest=/tmp copy=no

- name: build core module
  command: /opt/apache-maven-3.2.5/bin/mvn package
  args:
    chdir: /tmp/io-master/core/
    creates: /tmp/io-master/core/target/dc1-core.war
  environment:
    JAVA_HOME: /opt/jdk

- name: change core module's owner 
  file: "path=/tmp/io-master/core/target/dc1-core.war owner=glassfish group=glassfish mode=644"

- name: build engine
  command: /opt/apache-maven-3.2.5/bin/mvn package
  args:
    chdir: /tmp/io-master/engine
    creates: /tmp/io-master/engine/target/dc1-engine.war
  environment:
    JAVA_HOME: /opt/jdk

- name: change engine module's owner
  file: "path=/tmp/io-master/engine/target/dc1-engine.war owner=glassfish group=glassfish mode=644"

- name: stop tomcat's service
  service: name=tomcat state=stopped

- name: delete /opt/tomcat/webapps/dc1-core
  file: state=absent path=/opt/tomcat/webapps/dc1-core

- name: delete /opt/tomcat/webapps/dc1-engine
  file: state=absent path=/opt/tomcat/webapps/dc1-engine

- name: deploy core
  command: mv /tmp/io-master/core/target/dc1-core.war /opt/tomcat/webapps/dc1-core.war

- name: deploy engine
  command: mv /tmp/io-master/engine/target/dc1-engine.war /opt/tomcat/webapps/dc1-engine.war

- name: start tomcat's service
  service: name=tomcat state=started


